[package]
name = "wikimedia-template-introspector-core"
version = "0.1.0"
edition = "2021"

[dependencies]
regex = "1.10.5"
quote = "1.0.36"
syn = { version = "2.0.60", features = ["full", "extra-traits"] }
proc-macro2 = "1.0.82"