[package]
name = "wiki_data_extractor"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
reqwest = { version = "0.12", features = ["json"] }
url = "2.5.0" # Add url crate for URL parsing
wikipedia_extractor = { path = "../wikidata" }